# Nome do banco em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=andreggomes
spring.datasource.password=1234

# Permite ver o console no navegador em /h2-console
spring.h2.console.enabled=true

# Faz o Hibernate criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true